# 02 - Data Cleaning

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/air_quality_raw.csv")
print("Raw shape:", df.shape)
df.head()

Raw shape: (3314, 11)

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Amaravati,"Secretariat, Amaravati - APPCB",30-01-2024 10:00:00,16.515083,80.518167,CO,17.0,70.0,51.0
1,India,Andhra_Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",30-01-2024 10:00:00,14.675886,77.593027,PM10,45.0,109.0,70.0
2,India,Andhra_Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",30-01-2024 10:00:00,14.675886,77.593027,OZONE,2.0,59.0,26.0
3,India,Andhra_Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",30-01-2024 10:00:00,13.204880,79.097889,NO2,9.0,28.0,14.0
4,India,Andhra_Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",30-01-2024 10:00:00,13.204880,79.097889,SO2,5.0,24.0,10.0

In [2]:
# drop country column - it's just 'India' everywhere
df = df.drop(columns=["country"])
print(df.columns.tolist())

['state', 'city', 'station', 'last_update', 'latitude', 'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max', 'pollutant_avg']

In [3]:
# check missing values
df.isnull().sum()

state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    221
pollutant_max    221
pollutant_avg    221
dtype: int64

In [4]:
# fix state and city names - remove underscores, apply title case
df["state"] = df["state"].str.replace("_", " ").str.strip().str.title()
df["city"]  = df["city"].str.strip().str.title()
df["station"] = df["station"].str.strip()

print(sorted(df["state"].unique()))

['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamilnadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [5]:
# convert last_update to datetime
df["last_update"] = pd.to_datetime(df["last_update"], dayfirst=True)
print(df["last_update"].dtype)
print(df["last_update"].iloc[0])

datetime64[ns]
2024-01-30 10:00:00

In [6]:
# rows where min > max (data entry issues)
bad = df[df["pollutant_min"] > df["pollutant_max"]]
print("Bad rows:", len(bad))

Bad rows: 0

In [7]:
# drop rows where pollutant_avg is missing
before = len(df)
df = df.dropna(subset=["pollutant_avg"])
print("Rows removed:", before - len(df))
print("Shape after cleaning:", df.shape)

Rows removed: 221
Shape after cleaning: (3093, 10)

In [8]:
df = df.reset_index(drop=True)
df.to_csv("../data/processed/air_quality_cleaned.csv", index=False)
print("Saved to air_quality_cleaned.csv")

Saved to air_quality_cleaned.csv

In [9]:
df.head()

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Andhra Pradesh,Amaravati,"Secretariat, Amaravati - APPCB",2024-01-30 10:00:00,16.515083,80.518167,CO,17.0,70.0,51.0
1,Andhra Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",2024-01-30 10:00:00,14.675886,77.593027,PM10,45.0,109.0,70.0
2,Andhra Pradesh,Anantapur,"Gulzarpet, Anantapur - APPCB",2024-01-30 10:00:00,14.675886,77.593027,OZONE,2.0,59.0,26.0
3,Andhra Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",2024-01-30 10:00:00,13.204880,79.097889,NO2,9.0,28.0,14.0
4,Andhra Pradesh,Chittoor,"Gangineni Cheruvu, Chittoor - APPCB",2024-01-30 10:00:00,13.204880,79.097889,SO2,5.0,24.0,10.0